import day1 from './1.ts';
import day2 from './2.ts';
import day3 from './3.ts';
import day4 from './4.ts';
import day5 from './5.ts';
import day6 from './6.ts';
import day7 from './7.ts';
import day8 from './8.ts';
import day9 from "./9.ts";
import day10 from './10.ts';

day1();
day2();
day3();
day4();
day5();
day6();
day7();
day8();
day9();
day10();